pipeline {
    agent any

    environment {
        DOCKER_BUILDKIT='1'
    }

    stages {
        stage('Check Changes') {
            steps{
                script {
                    def changes = checkout scm
                    def changedFiles = changes?.changedFiles?.collect { it.path }
                    def frontendChanges = changedFiles?.findAll { it.startsWith('frontend/') }
                    
                    if (frontendChanges?.isEmpty()) {
                        currentBuild.result = 'NOT_BUILT'
                        echo 'No changes in frontend/ directory. Skipping build.'
                        currentBuild.displayName = '#${BUILD_NUMBER} (Skipped)'
                        return
                    }
                }
            }
        }

        stage('Build Docker Image') {
            steps {
                dir('frontend') {
                    script {
                        sh "docker build -t frontend:latest ."
                    }
                }
            }
        }

        stage('Deploy') {
            steps {
                sh 'docker rm -f frontend'
                sh 'docker run -d --name frontend -p {env.FRONTEND_PORT}:5173 frontend:latest'
            }
        }

        stage('Finish') {
            steps {
                sh 'docker images -qf dangling=true | xargs -I{} docker rmi {}'
            }
        }
    }
}
