version: '3.8'
services:
  nginx:
    image: nginx
    container_name: nginx
    ports:
      - 80:80
      - 443:443
    volumes:
      - ./infra/nginx/conf.d:/app
      - /etc/letsencrypt:/etc/letsencrypt
    restart: unless-stopped

  mariadb:
    image: mariadb
    container_name: mariadb
    environment:
      MARIADB_ROOT_PASSWORD: ${MARIADB_ROOT_PW}
      MARIADB_USER : ${MARIADB_USER}
      MARIADB_PASSWORD : ${MARIADB_PW}
      TZ: Asial/Seoul
    volumes:
      - mariadb_data:/var/lib/mysql
      - ./infra/mariadb/init:/docker-entrypoint-initdb.d
      - ./infra/mariadb/conf.d/mysql.cnf:/etc/mysql/mysql.cnf
    restart: unless-stopped
    networks:
      - mariadb_network

  jenkins:
    image: jenkins/jenkins:lts
    container_name: jenkins
    environment:
      FRONTEND_PORT: ${FRONTEND_PORT}
    volumes:
      # docker mount
      - /usr/bin/docker:/usr/bin/docker
      - /var/run/docker.sock:/var/run/docker.sock
      # docker plugin : docker compose(v2), docker buildx mounting
      - /usr/local/lib/docker/cli-plugins/docker-compose:/usr/local/lib/docker/cli-plugins/docker-compose
      - /usr/libexec/docker/cli-plugins/docker-buildx:/usr/libexec/docker/cli-plugins/docker-buildx
      # jenkins data 유지
      - /var/jenkins_home:/var/jenkins_home
      # flask, backend 빌드 컨테이너 환경변수
      - ./.env:/var/jenkins_home/workspace/dep-be/.env
      - ./.env:/var/jenkins_home/workspace/dep-flask/.env
      # backend application 환경변수
      - ./backend/src/main/resources:/var/jenkins_home/workspace/dep-be/backend/src/main/resources
      # frontend 배포 환경변수
      - ./frontend/.env.production:/var/jenkins_home/workspace/dep-fe/frontend/.env.production
      # nginx deploy conf files
      - /etc/letsencrypt:/etc/letsencrypt:z
      - ./infra/nginx:/var/jenkins_home/workspace/dep-be/infra/nginx:z
    ports:
      - ${JENKINS_PORT}:8080
    privileged: true
    user: ${JENKINS_USER}
    restart: unless-stopped

volumes:
  mariadb_data:

networks:
  mariadb_network:
    name: mariadb_network
    driver: bridge
