version: '3.8'
services:
  nginx_blue:
    image: nginx_blue
    container_name: nginx_blue
    ports:
      - 80:80
      - 443:443
    restart: unless-stopped
  
  backend_blue1:
    image: backend
    container_name: backend_blue1
    ports:
      - ${BACKEND_PORT_BLUE1}:8080
    networks:
      - mariadb_network
    restart: unless-stopped

  backend_blue2:
    image: backend
    container_name: backend_blue2
    ports:
      - ${BACKEND_PORT_BLUE2}:8080
    networks:
      - mariadb_network
    restart: unless-stopped

networks:
  mariadb_network:
    external: true