version: '3.8'
services:
  mariadb:
    image: mariadb
    container_name: mariadb
    environment:
      MARIADB_ROOT_PASSWORD: ${MARIADB_ROOT_PW}
      MARIADB_USER : ${MARIADB_USER}
      MARIADB_PASSWORD : ${MARIADB_PW}
      TZ: Asial/Seoul
    volumes:
      - mariadb_data:/var/lib/mysql
      # - ./infra/mariadb/conf.d:/etc/mysql/conf.d
      # - ./infra/mariadb/init:/docker-entrypoint-initdb.d
    # healthcheck:
    #   test: ['CMD-SHELL', 'mysqladmin ping -h 127.0.0.1 -u root --password=$$MARIADB_ROOT_PASSWORD']
    #   interval: 10s
    #   timeout: 5s
    #   retries: 5
    #   start_period: 30s
    restart: unless-stopped

  redis:
    image: redis:7.2.2-alpine3.18
    container_name: redis
    command: redis-server /usr/local/etc/redis/redis.conf
    volumes:
      - redis_data:/data
      - ./infra/redis/redis.conf:/usr/local/etc/redis/redis.conf
    networks:
      - redis_network
    restart: always

  jenkins:
    image: jenkins/jenkins:lts
    container_name: jenkins
    volumes:
      - /usr/bin/docker:/usr/bin/docker
      - /var/run/docker.sock:/var/run/docker.sock 
      - /var/jenkins_home:/var/jenkins_home
    ports:
      - ${JENKINS_PORT}:8080
    privileged: true
    user: ${JENKINS_USER}
    restart: unless-stopped

  nginx:
    image: nginx
    container_name: nginx
    ports:
      - 80:80
      - 443:443
    volumes:
      - ./etc/nginx:/etc/nginx/conf.d  
      - /etc/letsencrypt:/etc/letsencrypt 
    networks:
      - nginx_network
    restart: unless-stopped
    depends_on:
      - certbot

  certbot:
    image: certbot/certbot
    container_name: certbot
    volumes:
      - certbot_key:/etc/letsencrypt
      - certbot_var:/var/lib/letsencrypt
    command: certonly -d ${DOMAIN} --manual --preferred-challenges dns --server https://acme-v02.api.letsencrypt.org/directory
    tty: true
    stdin_open: true

volumes:
  mariadb_data:
  redis_data:
  certbot_key:
  certbot_var:

networks:
  nginx_network:
    name: nginx_network
    driver: bridge
  mariadb_network:
    name: mariadb_network
    driver: bridge
  redis_network:
    name: redis_network
    driver: bridge