CREATE DATABASE pnj DEFAULT CHARACTER SET utf8 COLLATE utf8_general_ci;
USE pnj;
GRANT ALL PRIVILEGES ON pnj.* TO 'ssafy'@'%';

CREATE TABLE `MEMBER` (
	`MEMBER_ID`	INT	NOT NULL,
	`EMAIL`	VARCHAR(255)	NULL,
	`NAME`	VARCHAR(255)	NULL,
	`UUID`	VARCHAR(255)	NULL,
	`ACCESS_TOKEN`	VARCHAR(255)	NULL,
	`REFRESH_TOKEN`	VARCHAR(255)	NULL
);

CREATE TABLE `TODOS` (
	`TODO_ID`	INT	NOT NULL,
	`MEMBER_ID`	INT	NOT NULL,
	`SUMMARY`	VARCHAR(255)	NULL
);

ALTER TABLE `MEMBER` ADD CONSTRAINT `PK_MEMBER` PRIMARY KEY (
	`MEMBER_ID`
);

ALTER TABLE `TODOS` ADD CONSTRAINT `PK_TODOS` PRIMARY KEY (
	`TODO_ID`
);

